version: '3'
services:
  node1:
    build: .
    ports:
     - "3001:3001"
  node2:
    build: .
    ports:
     - "3002:3001"
  node3:
    build: .
    ports:
     - "3003:3001"
  node4:
    build: .
    ports:
     - "3004:3001"
  node5:
    build: .
    ports:
     - "3005:3001"
